//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format specifier was invalid..
        /// </summary>
        internal static string Argument_BadFormatSpecifier {
            get {
                return ResourceManager.GetString("Argument_BadFormatSpecifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters following the format symbol must be a number of {0} or less..
        /// </summary>
        internal static string Argument_CannotParsePrecision {
            get {
                return ResourceManager.GetString("Argument_CannotParsePrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination is too short..
        /// </summary>
        internal static string Argument_DestinationTooShort {
            get {
                return ResourceManager.GetString("Argument_DestinationTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;G&apos; format combined with a precision is not supported..
        /// </summary>
        internal static string Argument_GWithPrecisionNotSupported {
            get {
                return ResourceManager.GetString("Argument_GWithPrecisionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use type &apos;{0}&apos;. Only value types without pointers or references are supported..
        /// </summary>
        internal static string Argument_InvalidTypeWithPointersNotSupported {
            get {
                return ResourceManager.GetString("Argument_InvalidTypeWithPointersNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlapping spans have mismatching alignment..
        /// </summary>
        internal static string Argument_OverlapAlignmentMismatch {
            get {
                return ResourceManager.GetString("Argument_OverlapAlignmentMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precision cannot be larger than {0}..
        /// </summary>
        internal static string Argument_PrecisionTooLarge {
            get {
                return ResourceManager.GetString("Argument_PrecisionTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot allocate a buffer of size {0}..
        /// </summary>
        internal static string BufferMaximumSizeExceeded {
            get {
                return ResourceManager.GetString("BufferMaximumSizeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot advance past the end of the buffer, which has a size of {0}..
        /// </summary>
        internal static string BufferWriterAdvancedTooFar {
            get {
                return ResourceManager.GetString("BufferWriterAdvancedTooFar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End position was not reached during enumeration..
        /// </summary>
        internal static string EndPositionNotReached {
            get {
                return ResourceManager.GetString("EndPositionNotReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equals() on Span and ReadOnlySpan is not supported. Use operator== instead..
        /// </summary>
        internal static string NotSupported_CannotCallEqualsOnSpan {
            get {
                return ResourceManager.GetString("NotSupported_CannotCallEqualsOnSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetHashCode() on Span and ReadOnlySpan is not supported..
        /// </summary>
        internal static string NotSupported_CannotCallGetHashCodeOnSpan {
            get {
                return ResourceManager.GetString("NotSupported_CannotCallGetHashCodeOnSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release all references before disposing this instance..
        /// </summary>
        internal static string OutstandingReferences {
            get {
                return ResourceManager.GetString("OutstandingReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected segment type..
        /// </summary>
        internal static string UnexpectedSegmentType {
            get {
                return ResourceManager.GetString("UnexpectedSegmentType", resourceCulture);
            }
        }
    }
}
